INT-8360: fix total null pointer exception
JupiterOne/graph-crowdstrike pull request #161
Opened 2023-07-04 15:23 UTC by mishelashala

2023-07-04 16:06 UTC, RonaldEAM requested changes

2023-07-04 16:06 UTC, RonaldEAM commented on src/crowdstrike/FalconAPIClient.ts
> +      if (this.totalCache[url] === undefined) {
Not sure if I understand the issue, but isn't this a different url string every time because of the query params? can you add some unit tests for this? They serve as a documentation on this logic

2023-07-04 18:24 UTC, mishelashala commented on src/crowdstrike/FalconAPIClient.ts
> +        this.totalCache[url] = paginationParams.total!;
Total will never change. But, under certain circumstances `paginationParams` will be `undefined`. That's why we are caching it. It seems to happen after a couple of iterations, so it is safe to assume it will not be `undefined` the first time

2023-07-04 18:26 UTC, mishelashala commented on src/crowdstrike/FalconAPIClient.ts
> +      if (this.totalCache[url] === undefined) {
Sure. I can work on that

2023-07-04 18:32 UTC, mishelashala commented on src/crowdstrike/FalconAPIClient.ts
> +        this.totalCache[url] = paginationParams.total!;
`seen` is like an `offset`, it serves a different purpose

2023-07-05 14:41 UTC, RonaldEAM approved these changes

2023-07-06 18:11 UTC, adam-in-ict commented on src/crowdstrike/CrowdStrikeApiGateway.ts
> +    const validUrls = /^api\.(\S+\.)?crowdstrike.com/;
Is there a reason we dismissed this warning instead of updating the regex?

2023-07-06 18:40 UTC, RonaldEAM requested changes

2023-07-06 18:40 UTC, RonaldEAM commented on package.json
> +    "sinon": "^15.2.0"
sinon and @types/sinon should be added as devDependencies

2023-07-06 18:40 UTC, RonaldEAM commented on src/crowdstrike/CrowdStrikeApiGateway.ts
> +    fetcher,
Why do you pass fetch in the constructor instead of importing it directly here?

2023-07-06 19:14 UTC, mishelashala commented on src/crowdstrike/CrowdStrikeApiGateway.ts
> +    fetcher,
So I can mock it

2023-07-06 19:15 UTC, mishelashala commented on package.json
> +    "sinon": "^15.2.0"
roger that

2023-07-06 20:17 UTC, RonaldEAM approved these changes

2023-07-06 20:24 UTC, merged

2023-07-11 16:57 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v3.7.0`](https://github.com/JupiterOne/graph-crowdstrike/releases/tag/v3.7.0) :rocket: